// seed.js - starter vocabulary cards (idioms, phrasal verbs & everyday words for casual native conversation)
(function () {
  window.SEED_CARDS = [
    { term: 'run into', meaning: '(人に)偶然会う、出くわす', example: 'I ran into my old classmate at the station yesterday.', type: 'idiom' },
    { term: 'figure out', meaning: '理解する、解決する', example: 'I finally figured out how to fix the printer.', type: 'idiom' },
    { term: 'catch up', meaning: '近況を語り合う、追いつく', example: "Let's grab coffee and catch up sometime this week.", type: 'idiom' },
    { term: "I'd rather", meaning: 'むしろ〜したい', example: "I'd rather stay home tonight than go to the party.", type: 'idiom' },
    { term: 'kind of', meaning: 'ちょっと、まあまあ', example: "I'm kind of tired after that long meeting.", type: 'idiom' },
    { term: 'it depends', meaning: '場合による', example: 'Do you want to go? It depends on the weather.', type: 'idiom' },
    { term: 'hang out', meaning: '遊ぶ、一緒に過ごす', example: 'We usually hang out at the mall on weekends.', type: 'idiom' },
    { term: 'look forward to', meaning: '楽しみにする', example: "I'm really looking forward to the trip next month.", type: 'idiom' },
    { term: 'end up', meaning: '結局〜になる', example: 'We ended up watching movies all night.', type: 'idiom' },
    { term: 'come up with', meaning: '(アイデアなどを)思いつく', example: 'She came up with a great plan for the party.', type: 'idiom' },
    { term: 'deal with', meaning: '対処する、扱う', example: 'I have to deal with a lot of emails today.', type: 'idiom' },
    { term: 'work out', meaning: 'うまくいく、運動する', example: "Don't worry, everything will work out fine.", type: 'idiom' },
    { term: 'turn out', meaning: '結局〜だとわかる', example: 'The movie turned out to be really good.', type: 'idiom' },
    { term: 'make sense', meaning: '筋が通る、納得できる', example: 'Your explanation makes a lot of sense.', type: 'idiom' },
    { term: 'no big deal', meaning: '大したことない', example: "Don't worry about it, it's no big deal.", type: 'idiom' },
    { term: 'on second thought', meaning: 'よく考えてみると', example: "On second thought, let's just stay in tonight.", type: 'idiom' },
    { term: 'give it a shot', meaning: 'とりあえずやってみる', example: "I've never tried sushi, but I'll give it a shot.", type: 'idiom' },
    { term: 'get along with', meaning: '(人と)うまくやる', example: 'I get along with most of my coworkers.', type: 'idiom' },
    { term: 'put off', meaning: '延期する、先延ばしにする', example: "Let's not put off this decision any longer.", type: 'idiom' },
    { term: 'show up', meaning: '姿を現す、来る', example: 'He didn\'t show up for the meeting this morning.', type: 'idiom' },
    { term: 'take off', meaning: '(仕事などを)休む、離陸する、脱ぐ', example: "I'm going to take a day off this Friday.", type: 'idiom' },
    { term: 'bring up', meaning: '話題に出す、育てる', example: "I don't want to bring up that topic again.", type: 'idiom' },
    { term: 'get over', meaning: '(病気や失恋から)立ち直る', example: 'It took her a while to get over the breakup.', type: 'idiom' },
    { term: 'count on', meaning: '頼りにする、当てにする', example: 'You can always count on me for help.', type: 'idiom' },
    { term: 'sort of', meaning: 'いくらか、まあまあ', example: "I'm sort of interested, but I'm not sure yet.", type: 'idiom' },
    { term: 'get used to', meaning: '〜に慣れる', example: 'It took a few weeks to get used to the new job.', type: 'idiom' },
    { term: 'pull off', meaning: '(難しいことを)成功させる', example: 'I can\'t believe she pulled off that presentation.', type: 'idiom' },
    { term: 'break a leg', meaning: '頑張って、成功を祈る', example: "You have a big audition tomorrow. Break a leg!", type: 'idiom' },
    { term: 'once in a while', meaning: 'たまに、時々', example: 'We go hiking once in a while on weekends.', type: 'idiom' },
    { term: 'piece of cake', meaning: '朝飯前、簡単なこと', example: "Don't worry, this test will be a piece of cake.", type: 'idiom' },
    { term: 'let someone down', meaning: '(人を)がっかりさせる', example: "I'm sorry, I didn't mean to let you down.", type: 'idiom' },
    { term: 'get carried away', meaning: '調子に乗る、我を忘れる', example: "Sorry, I got carried away talking about my trip.", type: 'idiom' },
    { term: 'up in the air', meaning: 'まだ未定である', example: 'Our vacation plans are still up in the air.', type: 'idiom' },
    { term: 'call it a day', meaning: '今日はここまでにする', example: "Let's call it a day and finish the rest tomorrow.", type: 'idiom' },
    { term: 'get the hang of', meaning: 'コツをつかむ', example: 'It took me a while to get the hang of using chopsticks.', type: 'idiom' },
    { term: 'in the long run', meaning: '長い目で見れば', example: 'Eating healthy will pay off in the long run.', type: 'idiom' },
    { term: 'keep in touch', meaning: '連絡を取り合う', example: "Let's keep in touch after graduation.", type: 'idiom' },
    { term: 'on the same page', meaning: '同じ考えで一致している', example: "Before we start, let's make sure we're on the same page.", type: 'idiom' },
    { term: 'off the top of my head', meaning: 'とっさに、すぐには思い出せないが', example: "I can't remember his number off the top of my head.", type: 'idiom' },
    { term: 'sleep on it', meaning: '一晩考える', example: "I'm not sure yet, let me sleep on it.", type: 'idiom' },
    { term: 'hit it off', meaning: 'すぐに意気投合する', example: 'We hit it off right away at the party.', type: 'idiom' },
    { term: 'wrap up', meaning: '終わらせる、まとめる', example: "Let's wrap up the meeting in five minutes.", type: 'idiom' },
    { term: 'run out of', meaning: '使い果たす、切らす', example: 'We ran out of milk this morning.', type: 'idiom' },
    { term: 'look up to', meaning: '尊敬する', example: "I've always looked up to my older sister.", type: 'idiom' },
    { term: 'back and forth', meaning: '行ったり来たり', example: 'We went back and forth about where to eat.', type: 'idiom' },
    { term: 'by the way', meaning: 'ところで', example: 'By the way, did you finish the report?', type: 'idiom' },
    { term: 'take it easy', meaning: '気楽にやる、無理しない', example: 'Take it easy this weekend, you deserve a break.', type: 'idiom' },
    { term: 'make up my mind', meaning: '決心する', example: "I still haven't made up my mind about the job offer.", type: 'idiom' },
    { term: 'give up', meaning: 'あきらめる', example: "Don't give up, you're almost done.", type: 'idiom' },
    { term: 'keep an eye on', meaning: '気をつけて見ておく', example: 'Can you keep an eye on my bag for a second?', type: 'idiom' },
    { term: 'get away with', meaning: '(悪いことをして)うまく逃れる', example: 'He always gets away with being late.', type: 'idiom' },
    { term: 'throw in the towel', meaning: 'あきらめる、降参する', example: 'After three failed attempts, she finally threw in the towel.', type: 'idiom' },
    { term: 'cut it close', meaning: 'ぎりぎりになる', example: 'We cut it close, but we made the train.', type: 'idiom' },
    { term: 'a long shot', meaning: '見込み薄、可能性が低い', example: 'Winning the lottery is a long shot.', type: 'idiom' },
    { term: 'out of the blue', meaning: '突然、予告なく', example: 'She called me out of the blue after years of silence.', type: 'idiom' },
    { term: 'in a nutshell', meaning: '一言で言うと、要するに', example: 'In a nutshell, the project was a success.', type: 'idiom' },
    { term: 'miss out on', meaning: '逃す、機会を失う', example: "I don't want to miss out on the fun.", type: 'idiom' },
    { term: 'drop by', meaning: 'ちょっと立ち寄る', example: 'Feel free to drop by anytime this week.', type: 'idiom' },
    { term: 'all set', meaning: '準備万端', example: 'Are you all set for the trip tomorrow?', type: 'idiom' },
    { term: 'hang in there', meaning: '頑張り続ける、持ちこたえる', example: "I know it's tough, but hang in there.", type: 'idiom' },
    { term: 'actually', meaning: '実は、実際は', example: "Actually, I've never tried sushi before.", type: 'word' },
    { term: 'apparently', meaning: 'どうやら〜らしい', example: 'Apparently, the store closed early today.', type: 'word' },
    { term: 'definitely', meaning: '間違いなく、絶対に', example: "I'll definitely be there by seven.", type: 'word' },
    { term: 'awkward', meaning: '気まずい、ぎこちない', example: 'There was an awkward silence after his joke.', type: 'word' },
    { term: 'hilarious', meaning: 'すごく面白い、爆笑もの', example: 'That video was absolutely hilarious.', type: 'word' },
    { term: 'exhausted', meaning: 'へとへとに疲れた', example: "I'm exhausted after that long flight.", type: 'word' },
    { term: 'decent', meaning: 'まあまあ良い、悪くない', example: 'The food at that restaurant was pretty decent.', type: 'word' },
    { term: 'random', meaning: '脈絡のない、適当な', example: 'He just said something totally random.', type: 'word' },
    { term: 'rough', meaning: 'つらい、大変な', example: "It's been a rough week at work.", type: 'word' },
    { term: 'overwhelmed', meaning: '圧倒された、手一杯な', example: "I feel overwhelmed with all this homework.", type: 'word' },
    { term: 'convenient', meaning: '便利な、都合の良い', example: 'This app makes ordering food really convenient.', type: 'word' },
    { term: 'annoying', meaning: '迷惑な、うっとうしい', example: "It's so annoying when my phone keeps buzzing.", type: 'word' },
    { term: 'obvious', meaning: '明らかな、当然の', example: 'It was obvious that she was upset.', type: 'word' },
    { term: 'gorgeous', meaning: 'とても美しい、素晴らしい', example: 'The sunset over the ocean was gorgeous.', type: 'word' },
    { term: 'tricky', meaning: '厄介な、扱いにくい', example: 'This question is a bit tricky to answer.', type: 'word' },
    { term: 'literally', meaning: '文字通り、マジで', example: 'I literally just finished my homework.', type: 'word' },
    { term: 'basically', meaning: '基本的に、要するに', example: 'Basically, we just need to double-check the numbers.', type: 'word' },
    { term: 'honestly', meaning: '正直に言うと', example: "Honestly, I don't really like spicy food.", type: 'word' },
    { term: 'slightly', meaning: '少し、わずかに', example: 'The room felt slightly cold when I walked in.', type: 'word' },
    { term: 'roughly', meaning: 'おおよそ、大体', example: 'The trip takes roughly two hours by train.', type: 'word' },
    { term: 'specific', meaning: '具体的な、特定の', example: 'Can you give me a more specific example?', type: 'word' },
    { term: 'awful', meaning: 'ひどい、最悪な', example: 'The weather was awful all weekend.', type: 'word' },
    { term: 'weird', meaning: '変な、奇妙な', example: 'That was such a weird dream I had last night.', type: 'word' },
    { term: 'comfortable', meaning: '快適な、心地よい', example: 'This chair is really comfortable to sit in.', type: 'word' },
    { term: 'exhausting', meaning: '疲れさせる、へとへとになる', example: 'Taking care of a newborn is exhausting.', type: 'word' },
    { term: 'embarrassing', meaning: '恥ずかしい、気まずい', example: 'It was embarrassing when I forgot his name.', type: 'word' },
    { term: 'ridiculous', meaning: 'ばかげた、とんでもない', example: 'The price of that hotel is ridiculous.', type: 'word' },
    { term: 'legit', meaning: '本物の、まともな(くだけた言い方)', example: 'That restaurant looks legit, let\'s try it.', type: 'word' },
    { term: 'genuine', meaning: '本物の、心からの', example: 'She gave a genuine smile when she saw us.', type: 'word' },
    { term: 'desperate', meaning: '必死の、切羽詰まった', example: "I'm getting desperate for a good night's sleep.", type: 'word' },
    { term: 'stubborn', meaning: '頑固な', example: 'My dad is too stubborn to ask for directions.', type: 'word' },
    { term: 'clumsy', meaning: '不器用な、そそっかしい', example: "I'm so clumsy, I dropped my phone again.", type: 'word' },
    { term: 'moody', meaning: '気分屋の、機嫌が変わりやすい', example: "He's been really moody lately.", type: 'word' },
    { term: 'picky', meaning: '好き嫌いが激しい、選り好みする', example: 'My little brother is such a picky eater.', type: 'word' },
    { term: 'blunt', meaning: '率直な、ずけずけ言う', example: "She's very blunt about what she thinks.", type: 'word' },
    { term: 'sarcastic', meaning: '皮肉っぽい', example: "Don't take him seriously, he's just being sarcastic.", type: 'word' },
    { term: 'cheesy', meaning: '陳腐な、ベタな', example: "That movie's ending was kind of cheesy.", type: 'word' },
    { term: 'cozy', meaning: '居心地の良い', example: 'Their living room is small but cozy.', type: 'word' },
    { term: 'spontaneous', meaning: '思いつきの、自然な', example: "Let's be spontaneous and go on a road trip.", type: 'word' },
    { term: 'flexible', meaning: '融通が利く、柔軟な', example: 'My work schedule is pretty flexible.', type: 'word' },
    { term: 'reliable', meaning: '信頼できる', example: "She's always been a reliable friend.", type: 'word' },
    { term: 'thoughtful', meaning: '思いやりのある', example: 'That was such a thoughtful gift.', type: 'word' },
    { term: 'considerate', meaning: '配慮のある、思いやりのある', example: "He's always considerate of other people's feelings.", type: 'word' },
    { term: 'straightforward', meaning: '単純明快な、率直な', example: 'The instructions were pretty straightforward.', type: 'word' },
    { term: 'exaggerate', meaning: '大げさに言う', example: "Don't exaggerate, it wasn't that bad.", type: 'word' },
    { term: 'assume', meaning: '思い込む、想定する', example: 'I assumed you already knew about the meeting.', type: 'word' },
    { term: 'mention', meaning: '言及する、ちょっと話す', example: 'She mentioned she might be late today.', type: 'word' },
    { term: 'suppose', meaning: '〜だと思う、想定する', example: 'I suppose we should get going soon.', type: 'word' },
    { term: 'bother', meaning: '悩ます、わざわざ〜する', example: "Don't bother waiting for me, I'll catch up.", type: 'word' },
    { term: 'gross', meaning: '気持ち悪い、嫌な', example: 'Ugh, that smell is so gross.', type: 'word' },
    { term: 'guess', meaning: '推測する、〜だと思う', example: 'I guess we should just wait and see.', type: 'word' },
    { term: 'struggle', meaning: '苦労する、奮闘する', example: 'I struggled to understand the lecture today.', type: 'word' },
    { term: 'handle', meaning: '対処する、扱う', example: 'She handled the situation really calmly.', type: 'word' },
    { term: 'manage', meaning: 'なんとかやり遂げる', example: 'I managed to finish the report on time.', type: 'word' },
    { term: 'avoid', meaning: '避ける', example: 'I try to avoid eating too much sugar.', type: 'word' },
    { term: 'ignore', meaning: '無視する', example: "Just ignore him, he's only joking.", type: 'word' },
    { term: 'complain', meaning: '文句を言う', example: 'He is always complaining about the weather.', type: 'word' },
    { term: 'apologize', meaning: '謝る', example: 'I should apologize for being so late.', type: 'word' },
    { term: 'appreciate', meaning: '感謝する、ありがたく思う', example: 'I really appreciate your help today.', type: 'word' },
    { term: 'chill', meaning: 'のんびりする、リラックスする', example: "Let's just chill at home this weekend.", type: 'word' }
  ];
})();
